<a href="https://colab.research.google.com/github/xdmaury/projeto-integrador/blob/main/Projeto_IntegradorII_Transporte_A%C3%A9reo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# UMA VISÃO DO CENÁRIO E DO IMPACTO DA PANDEMIA DO TRANSPORTE AÉREO DO ESTADO DE GOIÁS

#**Área temática**


Voos e operações aéreas



#**Conjunto de dados**

Dados Estatísticos do Transporte Aéreo

#**Nome da área de contato**

SAS/GEAC - GERÊNCIA DE ACOMPANHAMENTO DE MERCADO

**E-mail de contato da área:**

> geac@anac.gov.br

**Periodicidade de atualização:**

> Mensal

**Descrição:**

​Base de Dados Estatísticos do Transporte Aéreo​

> Fonte: [https://www.anac.gov.br](https://www.anac.gov.br/acesso-a-informacao/dados-abertos/areas-de-atuacao/voos-e-operacoes-aereas/dados-estatisticos-do-transporte-aereo/48-dados-estatisticos-do-transporte-aereo)

# Entendendo os Dados

In [ ]:
! python --version

Python 3.7.14

In [ ]:
# Download dataset
! wget https://sistemas.anac.gov.br/dadosabertos/Voos%20e%20operações%20aéreas/Dados%20Estat%C3%ADsticos%20do%20Transporte%20Aéreo/Dados_Estatisticos.csv

--2022-09-06 00:16:35--  https://sistemas.anac.gov.br/dadosabertos/Voos%20e%20opera%C3%A7%C3%B5es%20a%C3%A9reas/Dados%20Estat%C3%ADsticos%20do%20Transporte%20A%C3%A9reo/Dados_Estatisticos.csv
Resolving sistemas.anac.gov.br (sistemas.anac.gov.br)... 189.3.93.46
Connecting to sistemas.anac.gov.br (sistemas.anac.gov.br)|189.3.93.46|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 306133067 (292M) [application/octet-stream]
Saving to: ‘Dados_Estatisticos.csv’

Dados_Estatisticos. 100%[===================>] 291.95M   906KB/s    in 5m 34s

2022-09-06 00:22:11 (896 KB/s) - ‘Dados_Estatisticos.csv’ saved [306133067/306133067]

In [ ]:
# Importando Bibliotecas
import pandas as pd
pd.__version__

In [ ]:
# Importando Dataset
df = pd.read_csv('Dados_Estatisticos.csv', sep=';', skiprows=[0] )

In [ ]:
df.describe()

,ANO,MES,PASSAGEIROS_PAGOS,PASSAGEIROS_GRATIS,CARGA_PAGA_KG,CARGA_GRATIS_KG,CORREIO_KG,ASK,RPK,ATK,RTK,COMBUSTIVEL_LITROS,DISTANCIA_VOADA_KM,DECOLAGENS,CARGA_PAGA_KM,CARGA_GRATIS_KM,CORREIO_KM,ASSENTOS,PAYLOAD,BAGAGEM_KG
count,940172.000000,940172.000000,894899.000000,894899.000000,8.948990e+05,894899.000000,894899.000000,7.174580e+05,7.179330e+05,7.174580e+05,7.174470e+05,6.242140e+05,7.174580e+05,717994.000000,7.179330e+05,7.174470e+05,7.179330e+05,717993.000000,7.179930e+05,767108.000000
mean,2010.273004,6.447638,1962.453853,42.277190,2.488893e+04,245.977049,2439.310242,6.217284e+06,4.708494e+06,1.005635e+06,5.919220e+05,1.472731e+05,3.485379e+04,26.687939,1.620486e+08,7.160032e+05,6.075227e+06,3685.636251,4.680933e+05,22873.393664
std,6.338892,3.493356,4506.452179,153.038884,9.687561e+04,1971.726264,22779.403678,1.605027e+07,1.301874e+07,2.760325e+06,1.671380e+06,3.454552e+05,6.620211e+04,45.983501,7.174852e+08,9.326604e+06,4.700460e+07,7217.665269,8.304522e+05,51125.628111
min,2000.000000,1.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,-1.971210e+05,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000
25%,2005.000000,3.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,1.800000e+04,0.000000e+00,1.559800e+04,3.678000e+03,4.826000e+03,1.654000e+03,2.000000,0.000000e+00,0.000000e+00,0.000000e+00,68.000000,2.230400e+04,40.000000
50%,2010.000000,6.000000,203.000000,0.000000,4.300000e+01,0.000000,0.000000,5.108220e+05,2.884350e+05,1.334410e+05,5.819100e+04,2.574050e+04,8.672000e+03,11.000000,2.822010e+05,0.000000e+00,0.000000e+00,687.000000,1.369730e+05,2593.000000
75%,2015.000000,10.000000,1834.000000,21.000000,8.017000e+03,0.000000,0.000000,4.634880e+06,3.100920e+06,6.923348e+05,3.836120e+05,1.494828e+05,3.588300e+04,31.000000,1.807260e+07,0.000000e+00,0.000000e+00,4582.000000,5.558920e+05,20393.000000
max,2022.000000,12.000000,92357.000000,7452.000000,4.018286e+06,189562.000000,825678.000000,3.782380e+08,2.699140e+08,5.928730e+07,3.501670e+07,6.704640e+06,1.015740e+06,918.000000,2.108960e+10,1.373030e+09,2.750410e+09,154845.000000,2.319650e+07,919417.000000

In [ ]:
# Filtrando dados de GOIAS 
df_go = df.query('AEROPORTO_DE_ORIGEM_UF=="GO" or AEROPORTO_DE_DESTINO_UF=="GO"')

In [ ]:
df_go.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 28559 entries, 1156 to 939182
Data columns (total 38 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   EMPRESA_SIGLA                    28559 non-null  object
 1   EMPRESA_NOME                     28559 non-null  object
 2   EMPRESA_NACIONALIDADE            28559 non-null  object
 3   ANO                              28559 non-null  int64
 4   MES                              28559 non-null  int64
 5   AEROPORTO_DE_ORIGEM_SIGLA        28554 non-null  object
 6   AEROPORTO_DE_ORIGEM_NOME         28554 non-null  object
 7   AEROPORTO_DE_ORIGEM_UF           28530 non-null  object
 8   AEROPORTO_DE_ORIGEM_REGIAO       28530 non-null  object
 9   AEROPORTO_DE_ORIGEM_PAIS         28554 non-null  object
 10  AEROPORTO_DE_ORIGEM_CONTINENTE   28554 non-null  object
 11  AEROPORTO_DE_DESTINO_SIGLA       28559 non-null  object
 12  AEROPORTO_DE_DESTINO_NOME        28559 non-null  object
 13  AEROPORTO_DE_DESTINO_UF          28539 non-null  object
 14  AEROPORTO_DE_DESTINO_REGIAO      28539 non-null  object
 15  AEROPORTO_DE_DESTINO_PAIS        28559 non-null  object
 16  AEROPORTO_DE_DESTINO_CONTINENTE  28559 non-null  object
 17  NATUREZA                         28559 non-null  object
 18  GRUPO_DE_VOO                     28559 non-null  object
 19  PASSAGEIROS_PAGOS                27629 non-null  float64
 20  PASSAGEIROS_GRATIS               27629 non-null  float64
 21  CARGA_PAGA_KG                    27629 non-null  float64
 22  CARGA_GRATIS_KG                  27629 non-null  float64
 23  CORREIO_KG                       27629 non-null  float64
 24  ASK                              21041 non-null  float64
 25  RPK                              21041 non-null  float64
 26  ATK                              21041 non-null  float64
 27  RTK                              21041 non-null  float64
 28  COMBUSTIVEL_LITROS               21034 non-null  float64
 29  DISTANCIA_VOADA_KM               21041 non-null  float64
 30  DECOLAGENS                       21042 non-null  float64
 31  CARGA_PAGA_KM                    21041 non-null  float64
 32  CARGA_GRATIS_KM                  21041 non-null  float64
 33  CORREIO_KM                       21041 non-null  float64
 34  ASSENTOS                         21042 non-null  float64
 35  PAYLOAD                          21042 non-null  float64
 36  HORAS_VOADAS                     21037 non-null  object
 37  BAGAGEM_KG                       27611 non-null  float64
dtypes: float64(18), int64(2), object(18)
memory usage: 8.5+ MB

# 1. Quais os destinos mais procurados?

In [ ]:
#Filtrando dados em 5 anos
df_destino = df_go.query("ANO >= 2017 and ANO < 2022 and AEROPORTO_DE_DESTINO_UF != 'GO'")

In [ ]:
df_destino = df_destino[['AEROPORTO_DE_DESTINO_UF', 'PASSAGEIROS_PAGOS']].groupby(['AEROPORTO_DE_DESTINO_UF']).sum().reset_index()

In [ ]:
df_destino

   AEROPORTO_DE_DESTINO_UF  PASSAGEIROS_PAGOS
0                       AL             7513.0
1                       AM                0.0
2                       BA           171338.0
3                       CE            23759.0
4                       DF           680135.0
5                       ES              942.0
6                       MA                0.0
7                       MG           467375.0
8                       MS             8355.0
9                       MT           208184.0
10                      PA             7952.0
11                      PB               31.0
12                      PE           106072.0
13                      PI                0.0
14                      PR             5655.0
15                      RJ           315282.0
16                      RN            12062.0
17                      RO               99.0
18                      RR                0.0
19                      RS             7111.0
20                      SC             1564.0
21                      SE               29.0
22                      SP          4339221.0
23                      TO           218173.0

In [ ]:
df_destino.sort_values(by=['PASSAGEIROS_PAGOS'], inplace=True, ascending=False)

In [ ]:
! pip install pandas

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (1.3.5)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (2022.2.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (1.21.6)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas) (1.15.0)

In [ ]:
import plotly.express as px

fig = px.bar(df_destino, x='AEROPORTO_DE_DESTINO_UF', y='PASSAGEIROS_PAGOS')
fig.show()

In [ ]:
#Filtrando dados em 5 anos
df_regiao = df_go.query("ANO >= 2017 and ANO < 2022 and AEROPORTO_DE_DESTINO_UF != 'GO'")

In [ ]:
df_regiao = df_regiao[['AEROPORTO_DE_DESTINO_REGIAO', 'PASSAGEIROS_PAGOS']].groupby(['AEROPORTO_DE_DESTINO_REGIAO']).sum().reset_index()

In [ ]:
df_regiao.sort_values(by=['PASSAGEIROS_PAGOS'], inplace=True, ascending=False)

In [ ]:
import plotly.express as px

fig = px.bar(df_regiao, x='AEROPORTO_DE_DESTINO_REGIAO', y='PASSAGEIROS_PAGOS')
fig.show()

# 2. Qual é a época que mais transita passageiros?

In [ ]:
#Filtrando dados em 5 anos
df_epoca = df_go.query("ANO >= 2017 and ANO < 2022")

In [ ]:
df_epoca  = df_epoca[['ANO', 'MES', 'EMPRESA_SIGLA', 'PASSAGEIROS_PAGOS']].groupby(['ANO', 'MES']).sum().reset_index()

In [ ]:
df_epoca = df_epoca.groupby(['MES']).mean().drop(columns=['ANO']).reset_index()

In [ ]:
df_epoca

    MES  PASSAGEIROS_PAGOS
0     1           268582.6
1     2           207619.0
2     3           203392.8
3     4           170918.2
4     5           182386.0
5     6           188955.0
6     7           237854.8
7     8           218776.8
8     9           215796.6
9    10           230566.2
10   11           234104.4
11   12           264415.6

In [ ]:
import plotly.express as px

fig = px.bar(df_epoca, x='MES', y='PASSAGEIROS_PAGOS')
fig.show()

In [ ]:
df_geral = df.query("ANO >= 2017 and ANO < 2022")

In [ ]:
df_geral = df_geral[['ANO', 'MES', 'EMPRESA_SIGLA', 'PASSAGEIROS_PAGOS']].groupby(['ANO', 'MES']).sum().reset_index()

In [ ]:
df_geral = df_geral.groupby(['MES']).mean().drop(columns=['ANO']).reset_index()

In [ ]:
df_geral

    MES  PASSAGEIROS_PAGOS
0     1         10203304.4
1     2          8153356.0
2     3          7620121.0
3     4          6038765.6
4     5          6278671.8
5     6          6370205.8
6     7          8018047.4
7     8          7504462.6
8     9          7636452.2
9    10          8233805.0
10   11          8325814.8
11   12          9374567.2

In [ ]:
import plotly.express as px

fig = px.bar(df_geral, x='MES', y='PASSAGEIROS_PAGOS')
fig.show()

# 3. Quais grupos de voos mais transportam cargas pagas?

In [ ]:
#Filtrando dados em 5 anos
df_carga = df_go.query("ANO >= 2017 and ANO < 2022")

In [ ]:
df_carga = df_carga[['ANO','MES','GRUPO_DE_VOO', 'CARGA_PAGA_KM']].groupby(['ANO', 'MES', 'GRUPO_DE_VOO']).sum().reset_index()

In [ ]:
df_carga = df_carga.drop(df_carga[df_carga['GRUPO_DE_VOO']=='IMPRODUTIVO'].index)

In [ ]:
df_carga = df_carga.groupby(['ANO', 'GRUPO_DE_VOO']).sum().drop(columns='MES').reset_index()

In [ ]:
df_carga = df_carga

In [ ]:
import plotly.express as px

fig = px.bar(df_carga, x="ANO", y="CARGA_PAGA_KM",
             color='GRUPO_DE_VOO', barmode='group',
             height=600)
fig.show()

Nos ultimos 5 anos as 3 maiores empresas que transpotaram cargas pagas to Grupo de voos não regular

In [ ]:
df_carga_area = df_go[['ANO', 'MES', 'EMPRESA_NOME','GRUPO_DE_VOO', 'CARGA_PAGA_KM']].query("ANO >= 2017 and ANO < 2022 and GRUPO_DE_VOO =='NÃO REGULAR'").groupby(['ANO', 'EMPRESA_NOME']).sum().reset_index()

In [ ]:
anos = list(dict.fromkeys(df_carga_area['ANO'].values))

In [ ]:
# Obtendo as 3 empresas com mais cargas pagas por KM ao ano
lista = pd.DataFrame()
for ano in anos:
  maiores = df_carga_area.query(f'ANO == {ano}').sort_values(by=['CARGA_PAGA_KM'], ascending=False).head(3)
  lista = pd.concat([lista, maiores])

top3ciabyano = lista[['ANO', 'EMPRESA_NOME', 'CARGA_PAGA_KM']]

In [ ]:
import plotly.express as px

fig = px.bar(top3ciabyano, x="ANO", y="CARGA_PAGA_KM",
             color='EMPRESA_NOME', barmode='group',
             height=600)
fig.show()

# 4. Qual é variação das bagagens ao longo dos anos?

In [ ]:
#Filtrando dados
df_bagagem = df_go.query("ANO >= 2010 and ANO < 2022 and GRUPO_DE_VOO == 'REGULAR'")

In [ ]:
#Quantidade de compahias aereas por ano
df_qtd_cia = df_bagagem[[ "ANO", "EMPRESA_SIGLA"]].groupby(['ANO', "EMPRESA_SIGLA"]).count().reset_index()
df_qtd_cia = df_qtd_cia.groupby(['ANO']).count().reset_index()
df_qtd_cia.rename(columns={'EMPRESA_SIGLA': 'QTD_CIA'}, inplace=True)
df_qtd_cia

     ANO  QTD_CIA
0   2010        8
1   2011       10
2   2012        9
3   2013        9
4   2014        8
5   2015        7
6   2016        6
7   2017        5
8   2018        5
9   2019        5
10  2020        6
11  2021        7

In [ ]:
df_bagagem = df_bagagem[['ANO','MES', 'PASSAGEIROS_PAGOS', 'PASSAGEIROS_GRATIS', 'BAGAGEM_KG']].groupby(['ANO', 'MES']).sum().reset_index()

In [ ]:
df_bagagem

      ANO  MES  PASSAGEIROS_PAGOS  PASSAGEIROS_GRATIS  BAGAGEM_KG
0    2010    1           156989.0              2733.0   2393039.0
1    2010    2           135050.0              1722.0   1777491.0
2    2010    3           168520.0              2753.0   2280441.0
3    2010    4           169041.0              2804.0   2351663.0
4    2010    5           169688.0              2538.0   2369179.0
..    ...  ...                ...                 ...         ...
139  2021    8           195906.0              3479.0   1326978.0
140  2021    9           210613.0              3977.0   1476558.0
141  2021   10           222659.0              4487.0   1550910.0
142  2021   11           236065.0              4587.0   1689680.0
143  2021   12           264469.0              4492.0   2115650.0

[144 rows x 5 columns]

In [ ]:
df_bagagem = df_bagagem.groupby(['ANO']).sum().reset_index()

In [ ]:
df_bagagem['TOTAL_PASSAGEIROS'] = df_bagagem['PASSAGEIROS_PAGOS'] + df_bagagem['PASSAGEIROS_GRATIS']

In [ ]:
df_bagagem.insert(len(df_bagagem.columns), "QTD_CIA", df_qtd_cia['QTD_CIA'].values)

In [ ]:
df_bagagem

,ANO,MES,PASSAGEIROS_PAGOS,PASSAGEIROS_GRATIS,BAGAGEM_KG,TOTAL_PASSAGEIROS,QTD_CIA
0,2010,78,2102987.0,34144.0,30158480.0,2137131.0,8
1,2011,78,2563279.0,47775.0,36231453.0,2611054.0,10
2,2012,78,2819443.0,55592.0,36721252.0,2875035.0,9
3,2013,78,2747390.0,56839.0,32946960.0,2804229.0,9
4,2014,78,3142778.0,56796.0,36145196.0,3199574.0,8
5,2015,78,3129660.0,52878.0,35722695.0,3182538.0,7
6,2016,78,2873005.0,51022.0,32612925.0,2924027.0,6
7,2017,78,2936173.0,50322.0,30319458.0,2986495.0,5
8,2018,78,3059153.0,62382.0,26706129.0,3121535.0,5
9,2019,78,3131331.0,63259.0,22340616.0,3194590.0,5
10,2020,78,1347343.0,29645.0,8980186.0,1376988.0,6
11,2021,78,2043531.0,40368.0,14155479.0,2083899.0,7

In [ ]:
df_bagagem = df_bagagem.drop(columns=['MES', 'PASSAGEIROS_PAGOS', 'PASSAGEIROS_GRATIS'])

In [ ]:
import plotly.express as px

fig = px.line(df_bagagem, x='ANO', y='BAGAGEM_KG')
fig.show()

Esta relacionado com a quantidade de passageiros?

In [ ]:
df_bagagem.corr()

                        ANO  BAGAGEM_KG  TOTAL_PASSAGEIROS   QTD_CIA
ANO                1.000000   -0.795869          -0.195026 -0.765215
BAGAGEM_KG        -0.795869    1.000000           0.703947  0.493946
TOTAL_PASSAGEIROS -0.195026    0.703947           1.000000 -0.100709
QTD_CIA           -0.765215    0.493946          -0.100709  1.000000

#5. Qual é a variação de voos internos dentro do estado de GO?

In [ ]:
#Filtrando dados origem/destino GO  
df_periocidade_anual = df_go.query("GRUPO_DE_VOO == 'REGULAR' and AEROPORTO_DE_DESTINO_UF == 'GO' and AEROPORTO_DE_ORIGEM_UF == 'GO'")

In [ ]:
#Quantidade de voos
df_cia = df_periocidade_anual[[ "ANO", "EMPRESA_SIGLA"]].groupby(['ANO', "EMPRESA_SIGLA"]).count().reset_index()
df_cia = df_cia.groupby(['ANO']).count().reset_index()
df_cia.rename(columns={'EMPRESA_SIGLA': 'QTD_CIA'}, inplace=True)

In [ ]:
df_cia

     ANO  QTD_CIA
0   2000        3
1   2005        1
2   2006        1
3   2007        4
4   2008        2
5   2009        2
6   2010        4
7   2011        4
8   2012        5
9   2013        3
10  2014        2
11  2015        2
12  2016        1
13  2018        3
14  2019        2
15  2020        1

In [ ]:
import plotly.express as px
fig = px.scatter(df_cia, x="ANO", y="QTD_CIA")
fig.show()

# 6. Qual a variação de quantidade de companhias aéreas voando para Goiás, com voos regulares, nos últimos 20 anos, considerando periodicidade anual?

- Companhias aêras internacionais

- Filtrar por maiores que 5 decolagens

In [ ]:
#Filtrando dados em 5 anos
df_periocidade_anual = df_go.query("ANO < 2022 and GRUPO_DE_VOO == 'REGULAR' and AEROPORTO_DE_DESTINO_UF == 'GO' and DECOLAGENS > 5")

In [ ]:
#Quantidade de voos
df_cia = df_periocidade_anual[[ "ANO", "EMPRESA_SIGLA"]].groupby(['ANO', "EMPRESA_SIGLA"]).count().reset_index()
df_cia = df_cia.groupby(['ANO']).count().reset_index()

In [ ]:
df_cia.rename(columns={'EMPRESA_SIGLA': 'QTD_CIA'}, inplace=True)

In [ ]:
df_cia

     ANO  QTD_CIA
0   2000        7
1   2001        7
2   2002        7
3   2003        7
4   2004        6
5   2005        6
6   2006        7
7   2007        8
8   2008        7
9   2009        5
10  2010        6
11  2011        8
12  2012        8
13  2013        7
14  2014        7
15  2015        7
16  2016        6
17  2017        5
18  2018        5
19  2019        5
20  2020        4
21  2021        4

In [ ]:
import plotly.express as px
fig = px.scatter(df_cia, x="ANO", y="QTD_CIA")
fig.show()

# 7. Como varia a quantidade de passageiros transportados para as regiões?

In [ ]:
#Filtrando dados p/ regiao CENTRO-OESTE
df_centro_oeste = df_go.query("ANO > 2009 and GRUPO_DE_VOO == 'REGULAR' and AEROPORTO_DE_DESTINO_REGIAO == 'CENTRO-OESTE' and AEROPORTO_DE_DESTINO_UF != 'GO'")

In [ ]:
df_centro_oeste = df_centro_oeste[[ "ANO", "MES",  "PASSAGEIROS_PAGOS"]].groupby(['ANO', 'MES']).sum().reset_index()
df_centro_oeste

      ANO  MES  PASSAGEIROS_PAGOS
0    2010    1            26151.0
1    2010    2            23007.0
2    2010    3            29684.0
3    2010    4            29245.0
4    2010    5            28740.0
..    ...  ...                ...
144  2022    3            13345.0
145  2022    4            10251.0
146  2022    5             8931.0
147  2022    6             8951.0
148  2022    7            17866.0

[149 rows x 3 columns]

In [ ]:
import plotly.express as px

df = px.data.tips()
fig = px.box(df_centro_oeste, x='ANO', y="PASSAGEIROS_PAGOS")
fig.update_layout(title_text="CENTRO-OESTE")
fig.show()

In [ ]:
#Filtrando dados p/ regiao SUDESTE
df_sudeste = df_go.query("ANO > 2009 and GRUPO_DE_VOO == 'REGULAR' and AEROPORTO_DE_DESTINO_REGIAO == 'SUDESTE'")

In [ ]:
df_sudeste = df_sudeste[[ "ANO", "MES",  "PASSAGEIROS_PAGOS"]].groupby(['ANO', 'MES']).sum().reset_index()
df_sudeste

      ANO  MES  PASSAGEIROS_PAGOS
0    2010    1            47296.0
1    2010    2            43003.0
2    2010    3            52252.0
3    2010    4            52571.0
4    2010    5            53415.0
..    ...  ...                ...
146  2022    3            81991.0
147  2022    4            90477.0
148  2022    5            99445.0
149  2022    6            93668.0
150  2022    7           115516.0

[151 rows x 3 columns]

In [ ]:
import plotly.express as px

df = px.data.tips()
fig = px.box(df_sudeste, x='ANO', y="PASSAGEIROS_PAGOS")
fig.update_layout(title_text="SUDESTE")
fig.show()

In [ ]:
#Filtrando dados p/ regiao SUL
df_sul = df_go.query("ANO > 2009 and GRUPO_DE_VOO == 'REGULAR' and AEROPORTO_DE_DESTINO_REGIAO == 'SUL'")

In [ ]:
df_sul = df_sul[[ "ANO", "MES",  "PASSAGEIROS_PAGOS"]].groupby(['ANO', 'MES']).sum().reset_index()
df_sul

      ANO  MES  PASSAGEIROS_PAGOS
0    2010    3              221.0
1    2010    4              237.0
2    2010    5              298.0
3    2010    6              307.0
4    2010    7              392.0
..    ...  ...                ...
106  2019    8              143.0
107  2019   12               58.0
108  2020    4                0.0
109  2021   12              805.0
110  2022    1             3818.0

[111 rows x 3 columns]

In [ ]:
import plotly.express as px

df = px.data.tips()
fig = px.box(df_sul, x='ANO', y="PASSAGEIROS_PAGOS")
fig.update_layout(title_text="SUL")
fig.show()

In [ ]:
#Filtrando dados p/ regiao NORTE
df_norte = df_go.query("ANO > 2009 and GRUPO_DE_VOO == 'REGULAR' and AEROPORTO_DE_DESTINO_REGIAO == 'NORTE'")

In [ ]:
df_norte = df_norte[[ "ANO", "MES",  "PASSAGEIROS_PAGOS"]].groupby(['ANO', 'MES']).sum().reset_index()
df_norte

      ANO  MES  PASSAGEIROS_PAGOS
0    2010    1              768.0
1    2010    2              773.0
2    2010    3              836.0
3    2010    4              785.0
4    2010    5              925.0
..    ...  ...                ...
143  2022    3             1676.0
144  2022    4             1902.0
145  2022    5             2236.0
146  2022    6             2532.0
147  2022    7             2403.0

[148 rows x 3 columns]

In [ ]:
import plotly.express as px

df = px.data.tips()
fig = px.box(df_norte, x='ANO', y="PASSAGEIROS_PAGOS")
fig.update_layout(title_text="NORTE")
fig.show()

In [ ]:
#Filtrando dados p/ regiao Nordeste
df_nordeste = df_go.query("ANO > 2009 and GRUPO_DE_VOO == 'REGULAR' and AEROPORTO_DE_DESTINO_REGIAO == 'NORDESTE'")

In [ ]:
df_nordeste = df_nordeste[[ "ANO", "MES",  "PASSAGEIROS_PAGOS"]].groupby(['ANO', 'MES']).sum().reset_index()
df_nordeste

      ANO  MES  PASSAGEIROS_PAGOS
0    2010    1             1119.0
1    2010    2              930.0
2    2010    3             1110.0
3    2010    4              876.0
4    2010    5             1015.0
..    ...  ...                ...
139  2022    3            10618.0
140  2022    4            10041.0
141  2022    5             9862.0
142  2022    6             9455.0
143  2022    7            16138.0

[144 rows x 3 columns]

In [ ]:
import plotly.express as px

df = px.data.tips()
fig = px.box(df_nordeste, x='ANO', y="PASSAGEIROS_PAGOS")
fig.update_layout(title_text="NORDESTE")
fig.show()

# 8. A ocupação média dos voos tem relação com a quantidade de companhias aéreas em operação?

2010 - 2019

In [ ]:
#Filtrando dados em 10 anos 
df_ocupacao = df_go.query("ANO > 2009 and ANO < 2020 and PASSAGEIROS_PAGOS != 0")

In [ ]:
#Quantidade de compahias aereas por ano
df_qtd_cia = df_ocupacao[[ "ANO", "EMPRESA_SIGLA"]].groupby(['ANO', "EMPRESA_SIGLA"]).count().reset_index()
df_qtd_cia = df_qtd_cia.groupby(['ANO']).count().reset_index()
df_qtd_cia.rename(columns={'EMPRESA_SIGLA': 'QTD_CIA'}, inplace=True)
df_qtd_cia

    ANO  QTD_CIA
0  2010        9
1  2011       10
2  2012       10
3  2013        9
4  2014        7
5  2015        7
6  2016        7
7  2017        5
8  2018        5
9  2019        6

In [ ]:
df_ocupacao = df_ocupacao[[ "ANO", "MES", "PASSAGEIROS_PAGOS", 'PASSAGEIROS_GRATIS', 'ASSENTOS']].groupby(['ANO']).sum().reset_index()
df_ocupacao = df_ocupacao.drop(columns=['MES'])
df_ocupacao

    ANO  PASSAGEIROS_PAGOS  PASSAGEIROS_GRATIS   ASSENTOS
0  2010          2253082.0             34179.0  3740052.0
1  2011          2696140.0             47977.0  4398667.0
2  2012          2949445.0             55653.0  4748073.0
3  2013          2922380.0             57544.0  4275620.0
4  2014          3329506.0             57598.0  4542909.0
5  2015          3309212.0             54001.0  4564988.0
6  2016          3023586.0             51832.0  4165394.0
7  2017          3129136.0             52030.0  4131268.0
8  2018          3229932.0             64191.0  4274171.0
9  2019          3272981.0             64565.0  4237613.0

In [ ]:
df_ocupacao.insert(len(df_ocupacao.columns), "QTD_CIA", df_qtd_cia['QTD_CIA'].values)

In [ ]:
df_ocupacao['MEAN_OCUPACAO'] = (df_ocupacao['PASSAGEIROS_PAGOS'] + df_ocupacao['PASSAGEIROS_GRATIS'])/ df_ocupacao['ASSENTOS']

In [ ]:
df_ocupacao

,ANO,PASSAGEIROS_PAGOS,PASSAGEIROS_GRATIS,ASSENTOS,QTD_CIA,MEAN_OCUPACAO
0,2010,2253082.0,34179.0,3740052.0,9,0.611559
1,2011,2696140.0,47977.0,4398667.0,10,0.623852
2,2012,2949445.0,55653.0,4748073.0,10,0.632909
3,2013,2922380.0,57544.0,4275620.0,9,0.696957
4,2014,3329506.0,57598.0,4542909.0,7,0.745580
5,2015,3309212.0,54001.0,4564988.0,7,0.736741
6,2016,3023586.0,51832.0,4165394.0,7,0.738326
7,2017,3129136.0,52030.0,4131268.0,5,0.770022
8,2018,3229932.0,64191.0,4274171.0,5,0.770705
9,2019,3272981.0,64565.0,4237613.0,6,0.787600

In [ ]:
df_ocupacao[['ANO','QTD_CIA','MEAN_OCUPACAO']].corr()

                    ANO   QTD_CIA  MEAN_OCUPACAO
ANO            1.000000 -0.898016       0.947800
QTD_CIA       -0.898016  1.000000      -0.919247
MEAN_OCUPACAO  0.947800 -0.919247       1.000000

2012 - 2021

In [ ]:
#Filtrando dados em 10 anos 
df_ocupacao = df_go.query("ANO > 2010 and ANO < 2022 and PASSAGEIROS_PAGOS != 0")

In [ ]:
#Quantidade de compahias aereas por ano
df_qtd_cia = df_ocupacao[[ "ANO", "EMPRESA_SIGLA"]].groupby(['ANO', "EMPRESA_SIGLA"]).count().reset_index()
df_qtd_cia = df_qtd_cia.groupby(['ANO']).count().reset_index()
df_qtd_cia.rename(columns={'EMPRESA_SIGLA': 'QTD_CIA'}, inplace=True)
df_qtd_cia

     ANO  QTD_CIA
0   2011       10
1   2012       10
2   2013        9
3   2014        7
4   2015        7
5   2016        7
6   2017        5
7   2018        5
8   2019        6
9   2020        6
10  2021       12

In [ ]:
df_ocupacao = df_ocupacao[[ "ANO", "MES", "PASSAGEIROS_PAGOS", 'PASSAGEIROS_GRATIS', 'ASSENTOS']].groupby(['ANO']).sum().reset_index()
df_ocupacao = df_ocupacao.drop(columns=['MES'])
df_ocupacao

     ANO  PASSAGEIROS_PAGOS  PASSAGEIROS_GRATIS   ASSENTOS
0   2011          2696140.0             47977.0  4398667.0
1   2012          2949445.0             55653.0  4748073.0
2   2013          2922380.0             57544.0  4275620.0
3   2014          3329506.0             57598.0  4542909.0
4   2015          3309212.0             54001.0  4564988.0
5   2016          3023586.0             51832.0  4165394.0
6   2017          3129136.0             52030.0  4131268.0
7   2018          3229932.0             64191.0  4274171.0
8   2019          3272981.0             64565.0  4237613.0
9   2020          1404365.0             30153.0  1880117.0
10  2021          2080426.0             40640.0  2610091.0

In [ ]:
df_ocupacao.insert(len(df_ocupacao.columns), "QTD_CIA", df_qtd_cia['QTD_CIA'].values)

In [ ]:
df_ocupacao['MEAN_OCUPACAO'] = (df_ocupacao['PASSAGEIROS_PAGOS'] + df_ocupacao['PASSAGEIROS_GRATIS'])/ df_ocupacao['ASSENTOS']

In [ ]:
df_ocupacao

,ANO,PASSAGEIROS_PAGOS,PASSAGEIROS_GRATIS,ASSENTOS,QTD_CIA,MEAN_OCUPACAO
0,2011,2696140.0,47977.0,4398667.0,10,0.623852
1,2012,2949445.0,55653.0,4748073.0,10,0.632909
2,2013,2922380.0,57544.0,4275620.0,9,0.696957
3,2014,3329506.0,57598.0,4542909.0,7,0.745580
4,2015,3309212.0,54001.0,4564988.0,7,0.736741
5,2016,3023586.0,51832.0,4165394.0,7,0.738326
6,2017,3129136.0,52030.0,4131268.0,5,0.770022
7,2018,3229932.0,64191.0,4274171.0,5,0.770705
8,2019,3272981.0,64565.0,4237613.0,6,0.787600
9,2020,1404365.0,30153.0,1880117.0,6,0.762994
10,2021,2080426.0,40640.0,2610091.0,12,0.812641

In [ ]:
df_ocupacao[['ANO','QTD_CIA','MEAN_OCUPACAO']].corr()

                    ANO   QTD_CIA  MEAN_OCUPACAO
ANO            1.000000 -0.276220       0.909097
QTD_CIA       -0.276220  1.000000      -0.394225
MEAN_OCUPACAO  0.909097 -0.394225       1.000000

# 9. Existe correlação entre a companha aérea com mais voos e a quantidade de passageiros transportados?

In [ ]:
#Filtrando dados em 10 anos 
df_filter = df_go.query("ANO > 2009 and ANO < 2020")

In [ ]:
df_cia = df_filter[[ "ANO", "MES",  "EMPRESA_SIGLA"]].groupby(['ANO', 'EMPRESA_SIGLA']).count().reset_index()

In [ ]:
df_qtd_passageiro = df_filter[[ "ANO", "MES",  "EMPRESA_SIGLA", "PASSAGEIROS_PAGOS", "PASSAGEIROS_GRATIS"]].groupby(['ANO', 'EMPRESA_SIGLA']).sum().reset_index()
df_qtd_passageiro

     ANO EMPRESA_SIGLA   MES  PASSAGEIROS_PAGOS  PASSAGEIROS_GRATIS
0   2010           AZU   486           179819.0              2130.0
1   2010           GLO  1974           937281.0             21474.0
2   2010           ONE    24                0.0                 0.0
3   2010           PTB  1272           121537.0               733.0
4   2010           PUA    40              240.0                 0.0
..   ...           ...   ...                ...                 ...
81  2019           GLO  1419           852150.0             23020.0
82  2019           ONE    54            99270.0               450.0
83  2019           PTB   908            65445.0               153.0
84  2019           SID   388               98.0                 0.0
85  2019           TAM  1494          1002877.0              9147.0

[86 rows x 5 columns]

In [ ]:
df_qtd_passageiro = df_qtd_passageiro.groupby(['ANO']).sum().reset_index().drop(columns=['MES'])

In [ ]:
anos = list(dict.fromkeys(df_cia['ANO'].values))

In [ ]:
lista = []
for ano in anos:
  res = df_cia.query(f'ANO == {ano}')
  index = res['MES'].idxmax()
  lista.append(dict(res.loc[index]))

df_cia = pd.DataFrame(lista)

In [ ]:
df_cia.rename(columns={'MES': 'QTD_VOOS'}, inplace=True)

In [ ]:
df_cia

    ANO EMPRESA_SIGLA  QTD_VOOS
0  2010           GLO       294
1  2011           SLX       377
2  2012           SLX       393
3  2013           SLX       398
4  2014           AZU       480
5  2015           AZU       453
6  2016           AZU       472
7  2017           AZU       542
8  2018           AZU       609
9  2019           AZU       532

In [ ]:
df_cia['TOTAL_PASSAGEIROS_BY_ANO'] = df_qtd_passageiro['PASSAGEIROS_PAGOS'] + df_qtd_passageiro['PASSAGEIROS_GRATIS']
df_cia

    ANO EMPRESA_SIGLA  QTD_VOOS  TOTAL_PASSAGEIROS_BY_ANO
0  2010           GLO       294                 2288385.0
1  2011           SLX       377                 2744140.0
2  2012           SLX       393                 3005297.0
3  2013           SLX       398                 2980076.0
4  2014           AZU       480                 3387214.0
5  2015           AZU       453                 3363232.0
6  2016           AZU       472                 3075418.0
7  2017           AZU       542                 3181166.0
8  2018           AZU       609                 3294123.0
9  2019           AZU       532                 3337546.0

O fato da companhia fazer muitos **Voos** é determinante para a quantidade de passageiros transportados?

In [ ]:
df_cia.corr()

                               ANO  QTD_VOOS  TOTAL_PASSAGEIROS_BY_ANO
ANO                       1.000000  0.932185                  0.775401
QTD_VOOS                  0.932185  1.000000                  0.816874
TOTAL_PASSAGEIROS_BY_ANO  0.775401  0.816874                  1.000000